version: "3.4"

services:
  mysql:
    container_name: qwnts_slim_mysql
    image: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: qwnts
        MYSQL_USER: qwnts
        MYSQL_PASSWORD: password
        LANG: C.UTF-8
    volumes: 
       - ./docker/mysql/init:/docker-entrypoint-initdb.d

  php:
    container_name: qwnts_slim_php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/qwnts
    depends_on:
      - mysql

  nginx:
    container_name: qwnts_slim_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/qwnts
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
